name: Flujo de trabajo para PR a Master 1

on:
  pull_request_review:
  pull_request:
    branches:
      - master
    types: [opened,ready_for_review, synchronize, reopened,labeled,unlabeled]
jobs:
  reviewers:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: uesteibar/reviewer-lottery@v3
        with:
          repo-token: ${{ secrets.AUTO_REVIEWERS_TOKEN }}
